<?php

########################################################################
# Extension Manager/Repository config file for ext: "rm_staffmash"
#
# Auto generated by Extbase Kickstarter 2010-11-16
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Staffmash',
	'description' => 'Guess who\'s the collegue you\'re seeing',
	'category' => 'plugin',
	'author' => 'Rüdiger Marwein',
	'author_email' => '',
	'author_company' => '21TORR Interactive',
	'shy' => '',
	'dependencies' => 'cms,extbase,fluid,tt_address',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => 0,
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.0',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>